services:
  - type: web
    name: wenmai-e-platform
    runtime: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
